### ISSUE TITLE
Specific ROS2 Foxy Robot CPU “no rviz” and Host Desktop “rviz”only” Packages 

### ISSUE THREAD

**Issue by ARLunan** [luxonis/depthai-ros-examples#43] opened 2022-05-05 04:01 UTC
Create ROS2 Packages, 1) with an image Topic Publish only - “stereo_inertial_launch.py -no rviz node launch file to run on a Robot CPU, to publish topics to be displayed by a 2) new Package comprising reduced code “rviz only” launch.py file installed on a separate Host Desktop CPU that manages and controls the Robot.

**Comment by saching13** [comment] 2022-05-06 20:32
Duplicate of #42

**Closed as completed by saching13** 2022-05-06 20:32 UTC
Labels: duplicate
